### ISSUE TITLE
remove packing info

### ISSUE THREAD

**Issue by Licheng-Guo** [Blaok/haoda#2]
Change this to debug?
https://github.com/Blaok/haoda/blob/def55ac2875aae4c48a3ed3078e02c276f4d4a98/haoda/backend/xilinx.py#L156

**Comment by Blaok** [comment]
Sure

**Comment by Blaok** [comment]
Fixed in [0.0.20220404.dev1](https://github.com/Blaok/haoda/releases/tag/0.0.20220404.dev1)
